services:
  logs:
    build: .
    container_name: automatization-logs
    working_dir: /app/logging_task
    volumes:
      - .:/app
    command: ["poetry", "run", "python", "do_it_yourself.py"]

  tests:
    build:
      context: .
    container_name: automatization-tests
    working_dir: /app
    environment:
      PYTHONPATH: "."
    volumes:
      - .:/app
    command: /bin/sh -c "poetry install --no-root --with dev && poetry run pytest testing/test_name.py"
